services:
  springboot-app:
    build: .  # This will use your Dockerfile
    container_name: springboot-container
    ports:
      - "8088:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
